name: pre-commit

on:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadenlabs/action-pre-commit@0.2.0
        with:
          args: run --files
